# -*- coding: utf-8 -*-
"""init-dan-inheritance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/aliaaa909/009846c23328b22d198dff91558da0d2/init-dan-inheritance.ipynb
"""

class Kulkas:

  #class object attribute (attribute yang bersifat global untuk class kulkas)
  penjual = 'pak mamat'

  def __init__(self,harga, merek):
    self.harga = harga
    self.merek = merek
    self.garansi = 3
    self.tenaga = 'listrik'

  def keterangan(self, anak = 5 ):
    print(' kulkas merek {} harganya sebesar {} dan nama penjualnya {} yang punya {} anak'.format(self.merek,self.harga,self.penjual,anak))

barang = Kulkas(200, 'LG')

barang.keterangan(3)

"""**Inheritance**"""

class Mahasiswa:
  status = 'mahasiswa'

  def __init__ (self, nama, kelas):
    self.nama = nama
    self.kelas = kelas

  def keterangan(self):
    print('{} di kelas {} adalah seorang {}'.format(self.nama,self.kelas,self.status))

Joko = Mahasiswa('joko',12)

Joko.keterangan()

"""Fungsi super berfungsi untuk mencari data dari seluruh line di program python
dideklarasikan sbg super.__init__
___________________

pada class mahasiswa, data nilai dan kelas masih bisa kita lihat di fungsi init, makanya bisa dipanggil tanpa super, tapi kalau programnya panjang, kita bisa tinggal pake super tanpa nginget nama methodnya

"""

class Nilai(Mahasiswa):

    def __init__ (self, nama, kelas):
      #Mahasiswa.__init__(nama,kelas)
      super().__init__(nama,kelas)
      self.nilai_baru = []

    def input_nilai(self, tambah):
      return self.nilai_baru.append(tambah)

budi = Nilai('Budi',13)

budi.keterangan()

budi.input_nilai(80)

budi.nilai_baru